version: '3'

services:
  demo:
    image: demo-app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=demo-db
      - DB_USERNAME=demo-user
      - DB_PASSWORD=kygvthjtbvbdcnnnjj1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=b406adas45das45wqwqw_daa
  redis:
    image: bitnami/redis
    environment:
      - REDIS_PASSWORD=b406adas45das45wqwqw_daa
    ports:
      - "6379"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: kygvthjtbvbdcnnnjj1
      POSTGRES_USER: demo-user
      POSTGRES_DB: demo-db
    ports:
      - "5432"

