version: '3'

services:
  demo:
    image: demo-app
    env_file:
      - .env
    ports:
      - 80:8888
  redis:
    image: bitnami/redis
    volumes:
      - redis-data:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=b406adas45das45wqwqw_daa
    ports:
      - "6379"
  db:
    image: postgres
    restart: always
    volumes:
      - bd-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: kygvthjtbvbdcnnnjj1
      POSTGRES_USER: demo-user
      POSTGRES_DB: demo-db
    ports:
      - "5432"
volumes:
  redis-data:
  bd-data:
  