version: '3'

services:
  demo:
    image: demo-app
    env_file:
      - called.env
  redis:
    image: bitnami/redis
    environment:
      - REDIS_PASSWORD=b406adas45das45wqwqw_daa
    ports:
      - "6379"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: kygvthjtbvbdcnnnjj1
      POSTGRES_USER: demo-user
      POSTGRES_DB: demo-db
    ports:
      - "5432"

